### PR TITLE
Enhancement https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/issues/55

### PR DESCRIPTION
**Pull request by EWhite613**
... option to provide element opened by @knownasilya 

#minor# 

Also eslint fixes.
 
# Changelog
* Added the enhancement https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/issues/55 
  * Added option to provide DOM Element to target

### CODE REVIEW

**Comment by EWhite613** [comment]
Just need to update the README. And add a test for it

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by EWhite613** [comment]
Using this is the test https://jsfiddle.net/w3qzmcm7/ and targeting the right

**Comment by knownasilya** [comment]
That was the fastest implementation ever!

**Comment by EWhite613** [comment]
@knownasilya lol ya. But it seems Travis is having trouble, hasn't started the build still

**Comment by sglanzer** [comment]
Silly Travis - looking into it

**Comment by EWhite613** [comment]
@sglanzer good to review. Now that whole ember-cli broccoli dependency is resolved

**Comment by sglanzer** [comment]
Approved

**Pull request merged**
