### PR TITLE
Remove jquery

### PR DESCRIPTION
**Pull request by ro0gr**
#patch#
see #78

### CODE REVIEW

**Comment by EWhite613** [comment]
Sadly we're currently using in this file https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/blob/master/vendor/VisualAcceptance.js 

So gotta switch all that stuff to not use any jquery first

**Comment by ro0gr** [comment]
Ember provides it's own jquery. Looks like everything works without a separate instance. Maybe I'm missing something?

**Comment by ro0gr** [comment]
Anyways not using of jquery first sounds good for me :)

**Comment by EWhite613** [comment]
You're right. I think it was something with Phantomjs that I had to import jquery. My phantomjs is freaking out right now.

Once I figure out why my phantomjs isn't working and test v 1.9.8 and the latest 2.* I'll let you know. If it works with both those versions of PhantomJS I'll merge this in

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by EWhite613** [comment]
Works fine with both versions of phantomJS. 

Thanks @ro0gr 

👍

**Comment by sglanzer** [comment]
Approved - great initiative to reduce dependencies

**Pull request merged**
