### PR TITLE
Keep container fixed. Fix fixed items

### PR DESCRIPTION
**Pull request by EWhite613**
#patch#

Need to test some more. I don't know why https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/pull/73/files#diff-435ef62643883d72917b250165c56a8bL85 was ever there. I think it was a remanent from trying to get cross-os to work with no differences

Edit: https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/pull/73/files#diff-435ef62643883d72917b250165c56a8bL85
Apparently it's in there because of PhantomJS

### CODE REVIEW

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
## New

#### Firefox: fixed
 

#### Firefox: fixed-more
 

#### Chrome: fixed
 

#### Chrome: fixed-more
 

#### PhantomJS: fixed
 

#### PhantomJS: fixed-more
 

#### SlimerJS: fixed
 

#### SlimerJS: fixed-more
 

## Changed

### PhantomJS: svg
<table><tr> <td></td> <td></td> <td></td> </tr><tr> <td>Diff</td> <td>Current</td> <td>Baseline</td> </tr></table>
### PhantomJS: svg-experimental
<table><tr> <td></td> <td></td> <td></td> </tr><tr> <td>Diff</td> <td>Current</td> <td>Baseline</td> </tr></table>
### PhantomJS: capture right
<table><tr> <td></td> <td></td> <td></td> </tr><tr> <td>Diff</td> <td>Current</td> <td>Baseline</td> </tr></table>

**Comment by EWhite613** [comment]
@sglanzer Notice PhantomJS fixed `fixed` image is blank. Only 'downside'

**Comment by sglanzer** [comment]
Yeah, I'm good with Phantom being a second-class citizen, awesome work :)

**Comment by sglanzer** [comment]
Approved

**Comment by EWhite613** [comment]
Gonna hold off on merging for a bit. Need to do some tests with containers of a different size

**Comment by sglanzer** [comment]
Approved

**Comment by EWhite613** [comment]
@sglanzer got phantomJS to work. And got specifying the target size to work with this fix

**Comment by EWhite613** [comment]
Tested core and ui with the new changes and they both work

**Comment by sglanzer** [comment]
Approved - so much win

**Pull request merged**
