### PR TITLE
fix dependencies

### PR DESCRIPTION
**Pull request by EWhite613**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

* Fixes https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/issues/113

### CODE REVIEW

**Comment by notmessenger** [comment]
I am fine with these changes but since nothing has actually changed about the `sync-request` package will these changes actually do anything to resolve #113 ?

**Comment by visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by EWhite613** [comment]
@notmessenger sync-request is now in the dependencies (the diff just decided to show it in the most convoluted way) and will fix the whole cannot find the module, I tested it out and it worked.

**Comment by notmessenger** [comment]
👍

**Pull request merged**
