### PR TITLE
Don't overwrite comment on PR. Make new one

### PR DESCRIPTION
**Pull request by EWhite613**
#minor#

# Changelog
- No longer query to see if there is an existing comment (which is then overwritten). Just post a new comment

### CODE REVIEW

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by sglanzer** [comment]
Wouldn't this result in a whole stack of comments when we just want the latest result?  If this is addressing #90, then the issue is more that subsequent pushes have no images than it is that the comment is being overwritten.

**Comment by EWhite613** [comment]
@sglanzer So if the newest comment results in a "No Changes" comment, don't post and keep the previous?

Just realized this would be dumb in the case of build matrices any ways

**Comment by sglanzer** [comment]
@EWhite613 re: "No changes" - exactly - we want to see what the PR is going to do to the target branch, we don't really care what it did to the previous commit in the PR

**Comment by EWhite613** [comment]
@sglanzer @rox163 Little confused. Say if a have a test that says "color" to "colour" , resulting in a PR comment that shows changes. Then I add another commit that fixes the readme and now the PR says "No Changes"?

**Comment by EWhite613** [comment]
@sglanzer @rox163 or is it I have a pr that changes "color" to "colour", PR comment has changes.
Then I do another commit that changes "colour" back to "color" resulting in a "No Changes" PR comment (but you really wanna show the previous)?

**Comment by sglanzer** [comment]
Not quite the situation - we were pushing a number of updates to a PR (for modals) - the first push showed the visual report, all subsequent changes (including additional captures, modifications to existing captures, etc.) showed "No Changes"

**Comment by sglanzer** [comment]
Added a 👍 to the situation that applies above

**Comment by EWhite613** [comment]
Really? As long as the actual images aren't committed it should show up

**Comment by sglanzer** [comment]
Yeah, I was surprised as well ;)

We probably were doing something wrong, but that's the behavior I was seeing - @rox163 am I describing it correctly?

We commented out the captures in `ember-frost-modal`, but we could easily do a PR with 2 pushes, enable one capture per push and see what happens

**Comment by sglanzer** [comment]
I'll post the result here

**Comment by rox163** [comment]
Yep that sounds about right.

**Comment by rox163** [comment]
See this PR. https://github.com/ciena-frost/ember-frost-modal/pull/20  I added captures in more than one commit pushed to the PR. The acceptance tool overwrote its comment and said no changes. Locally I saw new captures when I ran the tests.

**Comment by sglanzer** [comment]
Started a new PR with one initial capture https://github.com/ciena-frost/ember-frost-modal/pull/27 will screencap the first result, then push with a second capture

**Comment by sglanzer** [comment]
image

Not a great capture, but at least a capture

**Comment by sglanzer** [comment]
Pushing the second

**Pull request closed without merging**
