### PR TITLE
Fix title

### PR DESCRIPTION
**Pull request by knownasilya**
#patch#

### CODE REVIEW

**Comment by EWhite613** [comment]
We use https://www.npmjs.com/package/pr-bumper#pull-requests . So you can just add `#patch#` to the PR description and then just restart the travis build

**Comment by knownasilya** [comment]
You'll have to restart it, since I don't have perms for travis.

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by sglanzer** [comment]
Approved - thanks!

**Pull request merged**
