### PR TITLE
Cleaner Report

### PR DESCRIPTION
**Pull request by EWhite613**
#patch#

### CODE REVIEW

**Comment by ember-cli-visual-acceptance** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
@ember-cli-visual-acceptance Grrr phantomjs looks totally different

**Comment by EWhite613** [comment]
@sglanzer Made the report fail on purpose so you can see both scenarios. https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/pull/32#issuecomment-228767856

**Comment by sglanzer** [comment]
Approved

**Pull request merged**
