### PR TITLE
Simplify capture method interface

### PR DESCRIPTION
**Pull request by dafortin**
#major#

* Simplify `capture` interface to wrap `ready`, `then` and `catch`

### CODE REVIEW

**Comment by sglanzer** [comment]
Love it, very nice simplification

**Comment by sglanzer** [comment]
Approved

**Comment by sglanzer** [comment]
@dafortin looks like there is still a build failure to be addressed here

**Comment by dafortin** [comment]
@sglanzer looking at it :)

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Pull request merged**
