### PR TITLE
Put `index.js` on a diet

### PR DESCRIPTION
**Pull request by ro0gr**
#patch#
Here I've extracted commands and some of utils to appropriate files. 
Now most of `index.js` stuff is related to `express` and `ember-cli` specific hooks.
In my opinion it allows to better understand the code base for new people like me.

### CODE REVIEW

**Comment by ro0gr** [comment]
@EWhite613 what should I do to make pass a "pr-bumper check" on travis?

**Comment by EWhite613** [comment]
@ro0gr just have to add `#patch#` to your description than restart the build. I just quickly appended it to your description.

Thanks for this much needed PR.

**Comment by ro0gr** [comment]
Just realized that could loose some of commits to index.js. Need some time to double-check.

**Comment by ro0gr** [comment]
argh... 
also ES6 syntax fails https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/pull/91/files#diff-7cde7bc8975aa91bb4ea2126f063dec2R1 :)
will fix

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by EWhite613** [comment]
Beautiful :+1:

**Comment by sglanzer** [comment]
Approved - this is significantly more legible, definitely appreciate the contribution!

**Pull request merged**
