### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by EWhite613**
#minor# 

# Changelog
* Add travis integration
* Extend detectjs to detect PhantomJS and SlimerJS
* Add Bluebird for PhantomJS Promises
* Add JQuery for PhantomJS
* Simpler Test added (Just a div now)
* Add SlimerJS launcher
* Replace ES6 javascript for PhantomJS with plain javascript
* Add Travis reporting tool

### CODE REVIEW

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
PR ember-cli-visual-acceptance Report

**Comment by sglanzer** [comment]
👍

**Pull request merged**
