### PR TITLE
Fix RSVP module reference

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [ ] #none# - documentation fixes and/or test additions
 - [x] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG
- Fixes https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/issues/103
- Fix RSVP reference and switch to `var Promise = require('es6-promise').Promise`

### CODE REVIEW

**Comment by EWhite613** [comment]
@ro0gr I assume this causes no problems right? I don't know why `utils.js` has the promise require while the other commands don't.  I assume its just an mistake to include one and not the others or if the `utils.js` isn't necessary. Eithier way this quick fix should do the trick.

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by juwara0** [comment]
@EWhite613 - Your updates fixed the issue I reported.

**Comment by ro0gr** [comment]
Looks like rsvp had been originally used in runCommand  https://github.com/EWhite613/ember-cli-visual-acceptance/commit/a81f308d1b474d95509c5c36b710526f36b0958c

I think it can be safely replaced with a project wide es6-promise.

**Comment by ro0gr** [comment]
@EWhite613 ^

**Pull request merged**
