### PR TITLE
Tweaks and docs for 'capture undefined' Eslint error.

### PR DESCRIPTION
**Pull request by eric-adstage**
### This project uses [semver](semver.org), please check the scope of this pr:
 - [x] #none# - documentation fixes and/or test additions
 - [ ] #patch# - backwards-compatible bug fix
 - [ ] #minor# - adding functionality in a backwards-compatible manner
 - [ ] #major# - incompatible API change

# CHANGELOG
- Tweaked the simple-test.js integration test file, as well as adding documentation for the `'capture' is not defined` ESLint error.

### CODE REVIEW

**Comment by eric-adstage** [comment]
@EWhite613 Looks like I need to somehow indicate that this is a Patch-level PR, per https://travis-ci.org/ciena-blueplanet/ember-cli-visual-acceptance/builds/241570258?utm_source=github_status&utm_medium=notification - can you advise on how I should go about doing that?

**Comment by EWhite613** [comment]
I modified the pr comment. Can you change the title of the section from `Troubleshooting` to `Linting`. Also, it would be beneficial to have a subsection of that with `#### ESLint` for the one you have. And another section `#### JSHint` (since not everyone uses eslint) and basically just state its `/* globals capture */` for that

**Comment by visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by eric-adstage** [comment]
Cool, done.

**Comment by eric-adstage** [comment]
@EWhite613 Anything else you need from me?

**Comment by EWhite613** [comment]
approved

**Pull request merged**
