### PR TITLE
CompanionRepo

### PR DESCRIPTION
**Pull request by EWhite613**
#minor#

Testing PR. Don't merge yet

### CODE REVIEW

**Comment by ember-cli-visual-acceptance** [comment]
PR ember-cli-visual-acceptance Report 
 [Imgur Album](undefined)

**Comment by ember-cli-visual-acceptance** [comment]
PR ember-cli-visual-acceptance Report

**Comment by EWhite613** [comment]
test-priv-raw

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
## Passed: 
 ### Addition Information: 
 
## Failed: 
 ### Addition Information: 
 <table><tr> <td></td> <td></td> <td></td> </tr><tr> <td>Diff</td> <td>Current</td> <td>Baseline</td> </tr></table>

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
## Passed: 
 ### Addition Information: 
 
## Failed: 
 ### Addition Information: 
 <table><tr> <td></td> <td></td> <td></td> </tr><tr> <td>Diff</td> <td>Current</td> <td>Baseline</td> </tr></table>

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
## Passed: 
 ### Addition Information: 
 
## Failed: 
 ### Addition Information: 
 <table><tr> <td></td> <td></td> <td></td> </tr><tr> <td>Diff</td> <td>Current</td> <td>Baseline</td> </tr></table>

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
## Passed: 
### Addition Information: 
 
## Failed: 
### Addition Information: 
 <table><tr> <td></td> <td></td> <td></td> </tr><tr> <td>Diff</td> <td>Current</td> <td>Baseline</td> </tr></table>

**Pull request closed without merging**
